name: Build Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_iOS:
    runs-on: macos-12

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Set up permissions
      run: chmod +x build-iOS.sh

    - name: Install ldid
      run: brew install ldid

    - name: Build
      run: ./build-iOS.sh

    - name: Prepare Theos
      uses: und3fined/theos-action@main

    - name: Build package
      run: |
        cd wapper
        rm -f packages/*
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: d3crypt-iOS
        path: ${{ github.workspace }}/wrapper/packages/*.deb
