name: Build Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # build_iOS:
  #   runs-on: macos-12

  #   steps:
  #   - name: Check out source code
  #     uses: actions/checkout@v2

  #   - name: Set up permissions
  #     run: chmod +x build-iOS.sh

  #   - name: Install ldid
  #     run: brew install ldid

  #   - name: Build
  #     run: ./build-iOS.sh

  #   - name: Prepare Theos
  #     uses: und3fined/theos-action@main

  #   - name: Build package
  #     run: |
  #       cd wrapper
  #       rm -f packages/*
  #       make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

  #   - name: Upload binary as artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: dev.und3fy.appdecrypt2
  #       path: ${{ github.workspace }}/wrapper/packages/*.deb

  build_openf:
    runs-on: macos-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: aarch64-apple-ios

    - name: Setup dependencies
      run: |
        clang --version
        # download https://github.com/frida/frida/releases/download/16.5.7/frida-core-devkit-16.5.7-ios-arm64.tar.xz with curl
        curl -L https://github.com/frida/frida/releases/download/16.5.7/frida-core-devkit-16.5.7-ios-arm64.tar.xz -o frida-core-devkit-16.5.7-ios-arm64.tar.xz
        tar -xf frida-core-devkit-16.5.7-ios-arm64.tar.xz
        curl -L https://github.com/frida/frida/releases/download/16.5.7/frida-gum-devkit-16.5.7-ios-arm64.tar.xz -o frida-gum-devkit-16.5.7-ios-arm64.tar.xz
        tar -xf frida-gum-devkit-16.5.7-ios-arm64.tar.xz

        ls -lah frida-core-devkit-16.5.7-ios-arm64
        ls -lah frida-gum-devkit-16.5.7-ios-arm64

        # copy frida headers
        cp -f frida-core-devkit-16.5.7-ios-arm64/frida-core.h /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/
        cp -rf frida-gum-devkit-16.5.7-ios-arm64/frida-gum.h /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/
        # copy frida libraries
        cp -f frida-core-devkit-16.5.7-ios-arm64/libfrida-core.a /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
        cp -f frida-gum-devkit-16.5.7-ios-arm64/libfrida-gum.a /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/

    - name: Build
      run: |
        cd openf
        cargo build --release --target aarch64-apple-ios

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: openf
        path: ${{ github.workspace }}/openf/target/release/openf
